name: Clone Repository
on: [push]
jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: pradeepkp1744/Terraform
