name: Clone Public Repository Workflow

on:
  push:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  job-public-repo-windows:
    runs-on: windows-latest
    steps:
      
      - name: Clone pradeepkp1744/Terraformcode PUBLIC repository
        uses: pradeepkp1744/githubactionsforclone@v2
        with:
          owner: 'pradeepkp1744'
          repository: 'Terraformcode'
      
      - name: Access cloned repository content
        run: |
          echo "ROOT"
          ls -la
          echo "CLONED REPO"
          cd Terraformcode
          ls -la
        shell: bash
